### ISSUE TITLE
I can help you with React Frontend Development

### ISSUE THREAD

**Issue by gradaom** [Borodin1/CoffeeStyle#1]
Hello there. Hope you are doing well.
I have over than 5 years of react frontend development experience , so I can help you perfectly.
Can we please talk more ?
Thank you.

**Comment by Borodin1** [comment]
Hi,it will be perfect for me. Do you have anyone messenger,where we can speak?  Do I owe you something for your help?

**Comment by gradaom** [comment]
Can we please do chat via telegram?

My telegram is @golden_t_s
